### ISSUE TITLE
Errors after installation: html2canvas.js not found, POST Internal Server Error

### ISSUE THREAD

**Issue by AntoninSlejska** [Dilden/Yii2-Feedback-Widget#1]
After installation and configuration of the Widget, I can see the the "Send Feedback" dialog, but it does not send any info. When I click "Send Feedback", then I see in the console the following error message:
GET https://localhost/yii/frontend/web/html2canvas.js?_=1452683194473 404 (Not Found)

(The addresse of the file is:
https://localhost/yii/vendor/dilden/yii2-feedback-widget/assets/html2canvas.min.js )

When I send the feedback, then I see in the console:
POST https://localhost/yii/frontend/web/site/feedback 500 (Internal Server Error)

(I have the action in SiteController.php):

```
public function actionFeedback()
{
    // ajax validation
    if (Yii::$app->request->isAjax) {
        $data = json_decode($_POST['feedback']);
        $htmlMail = '<h3>Test</h3>';

        // Send email with image attached as HTML file
        Yii::$app->mailer->compose()
            ->setFrom('antonin@slejska.eu')
            ->setTo('antonin@slejska.eu')
            ->setSubject('Response from EPAS')
            ->setHtmlBody($htmlMail)
            ->send();
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $data;
    }
    return false;
}
```

**Comment by Dilden** [comment]
In reference to your first error, this is an issue I've yet to resolve.

As for your 500 error,  have you configured the mailer in Yii2?

**Comment by AntoninSlejska** [comment]
I thought my mailer configuration is correct, but I have found there a problem. Now I receive no 500 error. Thanks.

**Comment by AntoninSlejska** [comment]
I tested it more thoroughly. The e-mails are sent, but only from the startpage. In console I see both error messages. After I send a mesage, I become in the dialogue the following message: 'Sadly an error occured while sending your feedback. Please try again.' This message I get even when the e-mail is sent.

**Comment by AntoninSlejska** [comment]
After changing the ajaxURLpath to absolute, are the e-mails sent from all pages:

```
echo DildenFeedback::widget([
    'ajaxURL' => yii\helpers\BaseUrl::home(true) . 'site/feedback',
    'highlightElement' => 0,
]);
```

But I still receive the **POST https://localhost/yii/frontend/web/site/feedback 500 (Internal Server Error)** in console and in the dialogue  **Sadly an error occured while sending your feedback. Please try again.**

**Comment by AntoninSlejska** [comment]
The error message html2canvas not found is solved by the patch https://github.com/Dilden/Yii2-Feedback-Widget/pull/5 .
(only typo, but I needed one hour to find it :-)

**Comment by AntoninSlejska** [comment]
The second problem is solved by the patch: https://github.com/Dilden/Yii2-Feedback-Widget/pull/6

Everything works perfect now.
