### ISSUE TITLE
How can I localise the widget?

### ISSUE THREAD

**Issue by AntoninSlejska** [Dilden/Yii2-Feedback-Widget#2]
The "Send feedback" button can be translated as follows:

```
echo DildenFeedback::widget([
    'ajaxURL' => 'site/feedback',
    'highlightElement' => 0,
    'initButtonText' => 'Feedback schicken',
]);
```

But how can I translate the texts, which are in the class DildenFeedback in the function init():

```
public function init() {
    $this->tpl['description']  = '<div id="feedback-welcome"> ...
}
```

**Comment by Dilden** [comment]
I've not yet gotten around to allow the changing of these values. However, you can still use https://github.com/ivoviz/feedback until this plugin is finished. That is where this widget is taken from.

If you'd like to work on adding these features, I'd be more than happy to work on them with you and test your code out. I've just been swamped with stuff lately and haven't had a chance to revisit this plugin. Now that I know someone else is using it though, I'll be sure to take another look at it.

**Comment by AntoninSlejska** [comment]
I will use the widget in my recent project. I will send you pull requests, when I have some improvements. Thanks...

**Comment by Dilden** [comment]
This issue should be resolved with the latest version that I've pushed up.
