### ISSUE TITLE
Conflict with yii\bootstrap\Modal

### ISSUE THREAD

**Issue by AntoninSlejska** [Dilden/Yii2-Feedback-Widget#7]
When a modal window is opened, then the screenshot is created, but it is not possible to write the feedback. There is some conflict between the yii\bootstrap\Modal and ivoviz/feedback.

In my installation I resolved the conflict, that after creating the screenshot I close the modal window. It is not general solution, but I have not found anything better.

**1. In all modal popups I added an id to the close button:**

```
Modal::begin([
    'header' => '<h2>Title</h2>',
    'toggleButton' => ['label' => 'Show the popup'],
    'closeButton' => ['id' => 'modal-close-button'],
]);
```

**2. Then I added a 'click' to the feedback.(min.)js:**

```
$(document).on('click', '#feedback-highlighter-next', function() {
    $('#modal-close-button')[0].click();
    ...
```

**Comment by Dilden** [comment]
Haven't had a chance to get around to this one but should have some time in the coming weeks. As for the ivoviz/feedback repo, I think it's been abandoned. The issues are most likely stemming from the original plugin as this one is just a skin for Yii2.

**Comment by AntoninSlejska** [comment]
The ivoviz/feedback is unmaintained, but some forks try to develop the app further, e.g.: https://github.com/JoeyAndres/feedback-tool

I know, that this issue is not directly related to this widget. I have published it primarily as an information for other developers, who would register the same problems.

**Comment by Dilden** [comment]
Do you think switching to that repository would solve the issues you've run into?

**Comment by JoeyAndres** [comment]
I'll look into this tomorrow and see what's going on.
